<a href="https://colab.research.google.com/github/jringler30/Colab_projects/blob/main/CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
custom_kernel = np.array([[1, 0, -1],
                          [1, 0, -1],
                          [1, 0, -1]], dtype=np.float32)

In [ ]:
custom_kernel = custom_kernel.reshape((3, 3, 1, 1))  # Shape: (3 height,3 width,1 input channels,1 output channesl)

In [ ]:
conv_layer = tf.keras.layers.Conv2D(filters=1, kernel_size=(3,3), use_bias=False)

In [ ]:
conv_layer.build(input_shape=(None, 5, 5, 1))  # Define input shape: (batch_size, height, width, channels)

In [ ]:
conv_layer.set_weights([custom_kernel])

In [ ]:
# Sample 5x5 grayscale image (random example)
input_image = np.array([[1, 2, 3, 0, 1],
                         [4, 5, 6, 1, 2],
                         [7, 8, 9, 2, 3],
                         [1, 2, 3, 4, 5],
                         [6, 7, 8, 9, 0]], dtype=np.float32)

# Reshape to match Keras input format: (batch_size, height, width, channels)
input_image = input_image.reshape((1, 5, 5, 1))

# Apply convolution
output_feature_map = conv_layer(input_image)

# Convert result to numpy
output_feature_map = output_feature_map.numpy().squeeze()  # Remove extra dimensions for readability
print("Feature Map:\n", output_feature_map)

Feature Map:
 [[-6. 12. 12.]
 [-6.  8.  8.]
 [-6.  2. 12.]]
